name: Google Job Tracker
on:
  schedule:
    - cron: '0 10 * * *' # Runs daily at 10 AM UTC
  workflow_dispatch:

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-jobspy requests pyyaml pandas
          echo "::add-mask::${{ secrets.TELEGRAM_TOKEN }}"

      - name: Run Tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          PYTHONUNBUFFERED: "1"
        run: python tracker.py

      - name: Save History & Push Changes
        run: |
          git config --global user.name "Z E U S B O T"
          git config --global user.email "zeusbot@atomicmail.io"
          
          if [ -f sent_jobs.txt ]; then
            git add sent_jobs.txt
            git diff --quiet && git diff --staged --quiet || (git commit -m "Update job history [skip ci]" && git push)
          fi
